enrollmentsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authority import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
)

urlpatterns = [
    path('', include('pages.urls')),
    #path('records/', include('records.urls')),
    #path('accounts/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path(
        'accounts/login/',
        LoginView.as_view(template_name='registration/login.html'),
        name='login',
    ),
    path("accounts/register", views.register_request, name="register"),
    path("accounts/myaccount/",
         views.user_profile, name="myaccount"),
    path("accounts/application", views.my_application, name="application"),
    path('enrollment/', include('records.urls', namespace='records')),
    path(
        'accounts/logout/',
        LogoutView.as_view(),
        name='logout',
    ),
    path("accounts/downloadform", views.download_form, name="download-form"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

records/urls.py
from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
    path('', views.enrollment, name='enrollment'),
    #path('<int:record_id>', views.record, name='record'),
    path('add/', views.RecordCreateView.as_view(), name='record-add'),
    path('get_enrollment/', views.get_enrollment, name='get-enrollment'),
    path('enrollment/<int:pk>/',
         views.RecordUpdateView.as_view(), name='record-update'),
    path('enrollment/<int:pk>/delete/',
         views.RecordDeleteView.as_view(), name='record-delete'),
]

templates/partials/_about.html
<section class="feature-column">
  <div class="container">
    <div class="row">
      <div class="feature-col col-sm-4" style="background-color: #007205">
        <div
          class="feature-col-item init-animate slideInUp1"
          style="visibility: visible; animation-name: slideInUp"
        >
          <h4>
            <a href="https://cvsu.edu.ph/mission/" rel="bookmark">Mission</a>
          </h4>
          <p>
            Cavite State University shall provide excellent, equitable and
            relevant educational opportunities in the arts, sciences and
            technology through quality instruction and responsive research and
            development activities. It shall produce professional, skilled and
            morally upright individuals for global competitiveness.
          </p>
        </div>
      </div>
      <div class="feature-col col-sm-4" style="background-color: #feb04d">
        <div
          class="feature-col-item init-animate slideInUp1"
          style="visibility: visible; animation-name: slideInUp"
        >
          <h4>
            <a href="https://cvsu.edu.ph/vision/" rel="bookmark">Vision</a>
          </h4>
          <p>
            The premier university in historic Cavite recognized for excellence
            in the development of globally competitive and morally upright
            individuals
          </p>
        </div>
      </div>
      <div class="feature-col col-sm-4" style="background-color: #3a5938">
        <div
          class="feature-col-item init-animate slideInUp1"
          style="visibility: visible; animation-name: slideInUp"
        >
          <h4>
            <a href="https://cvsu.edu.ph/quality-policy/" rel="bookmark"
              >Quality Policy</a
            >
          </h4>
          <p>
            We Commit to the highest standards of education, value our
            stakeholders, Strive for continual improvement of our products and
            services, and Uphold the University’s tenets of Truth, Excellence,
            and Service to produce globally competitive and morally upright
            individuals.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" roll="alert">
                <button class="close" type="button" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.leve. == DEFAULT_MESSAGE_LEVEL.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags | title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-1 bg-primary text-white text-center">
  Copyright &copy;
  <span class="year"></span> CVSU Enrollment System
</footer>

templates/partials/_modals.html
<!-- Scrollable modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">CvSU Online Enrollment System</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ul>
                    <li>THIS ADMISSION PROCESS IS FOR THE <b>1st SEMESTER OF 2022-2023</b>.</li>
                    <li>THE SYSTEM IS EXCLUSIVE FOR <b>NEW INCOMING FIRST YEAR STUDENTS, TRANSFEREES, SECOND COURSERS AND TCP APPLICANTS.</b></li>
                    <li>If you are a <b>shiftee or an old student</b> that is enrolled or was enrolled in CvSU, <b>DO NOT USE THIS SYSTEM</b></li>
                    <li>Use only one email address in the application and remember well your password. We prohibit the applicant to use multiple email addresses in order to create another account with same name. Once we traced that multiple entry of same name, we will only acknowledge the first entry and disregard the rest.</li>
                    <li>Applicants are prohibited from sharing the same email address to other applicants. Use your own email address in applying.</li>
                    <li>Input all your information with honesty and integrity. The data encoded and submitted documents will be subjected for validation and verification to your school.</li>
                    <li>Applicants who will violate the aforementioned guidelines will be disqualified from the list of application.
                    </li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">OK</button>
            </div>
        </div>    
    </div>
</div>

templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static 'img/diit.png' %}" class="logo" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li {% if '/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li {% if 'enrollment' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif%}>
          <a class="nav-link" href="{% url 'records:enrollment' %}">Enrollment</a>
        </li>
        <li {% if 'about' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">

        {% if user.is_authenticated %}          
          <li class="nav-item active mr-3 text-white">
            {{ user.email }}
            <a href="{% url 'logout' %}" style="color:red">Log Out</a>
          </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

templates/partials/_sidebar.html
{% load static %}
<style>
    .nav-link{
        color:white;
    }

    .nav-link:hover{
        color:lime;
    }
    .sidebar-icon{
        max-width:50%;
    }
</style>

<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
        <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
            <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <span class="fs-5 d-none d-sm-inline">
                    <img src="{% static 'img/diit.png' %}" class="mx-auto d-block sidebar-icon" alt="cvsu logo">
                </span>
            </a>
            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                <li class="nav-item">
                    <a href="{% url 'index' %}" class="nav-link align-middle px-0">
                        <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                    </a>
                </li>

                {% if user.is_authenticated %}
                <li>
                    <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                        <i class="bi bi-book-half"></i> <span class="ms-1 d-none d-sm-inline">Enrollment</span> </a>
                    <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                        <li class="w-100">
                            <a href="{% url 'records:record-add' %}" class="nav-link px-0"> <span class="d-none d-sm-inline">New Enrollment</span></a>
                        </li>
                        <li>
                            <a href="{% url 'records:enrollment' %}" class="nav-link px-0"> <span class="d-none d-sm-inline">My Enrollments</span></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                        <i class="bi bi-person-circle"></i><span class="ms-1 d-none d-sm-inline"> My Account</a>
                        <ul class="collapse show nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="{% url 'myaccount' %}" class="nav-link align-middle px-0"> <span class="d-none d-sm-inline">Student Info</span></a>
                            </li>
                            <li>
                                <a href="{% url 'application' %}" class="nav-link align-middle px-0"> <span class="d-none d-sm-inline">Application Forms</span></a>
                            </li>
                        </ul>
                </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link align-middle px-0">
                            <i class="bi bi-box-arrow-in-right"></i><span class="ms-1 d-none d-sm-inline">Sign in</span>
                            
                        </a>
                    </li>
                {% endif %}
                
                <li>
                    <a href="{% url 'about' %}" class="nav-link px-0 align-middle">
                        <i class="bi bi-question-circle-fill"></i> <span class="ms-1 d-none d-sm-inline">About</span> </a>
                </li>
            </ul>
            <hr>
            <ul class="navbar-nav ml-auto pb-3">

                {% if user.is_authenticated %}
                    <li class="nav-item active mr-3 text-white">
                        Signed in as : <br>{{ user.email }}
                    </li>
                    <li class="nav-item mr-3 text-white">
                        <i class="bi bi-box-arrow-left"></i>
                        <span class="ms-1 d-none d-sm-inline">
                            <a href="{% url 'logout' %}" style="color:red">Log Out</a>
                        </span>
                    </li>
                {% endif %}
        
              </ul>
            <!-- <div class="dropdown pb-4">
                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                    <span class="d-none d-sm-inline mx-1">loser</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </div> -->
        </div>
    </div>