enrollmentsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authority import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
)

urlpatterns = [
    path('', include('pages.urls')),
    #path('records/', include('records.urls')),
    #path('accounts/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path(
        'accounts/login/',
        LoginView.as_view(template_name='registration/login.html'),
        name='login',
    ),
    path("accounts/register", views.register_request, name="register"),
    path("accounts/myaccount/",
         views.user_profile, name="myaccount"),
    path("accounts/application", views.my_application, name="application"),
    path('enrollment/', include('records.urls', namespace='records')),
    path(
        'accounts/logout/',
        LogoutView.as_view(),
        name='logout',
    ),
    path("accounts/downloadform", views.download_form, name="download-form"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

records/urls.py
from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
    path('', views.enrollment, name='enrollment'),
    #path('<int:record_id>', views.record, name='record'),
    path('add/', views.RecordCreateView.as_view(), name='record-add'),
    path('get_enrollment/', views.get_enrollment, name='get-enrollment'),
    path('enrollment/<int:pk>/',
         views.RecordUpdateView.as_view(), name='record-update'),
    path('enrollment/<int:pk>/delete/',
         views.RecordDeleteView.as_view(), name='record-delete'),
]

records/models.py
import datetime
from enum import unique
from django.utils.timezone import now
from unittest.util import _MAX_LENGTH
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from authority.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import signals
from django.utils.translation import gettext_lazy as _


TRANSFEREE_INDEX = 3

SEMESTER_CHOICES = [
    (1, 1),
    (2, 2),
]

YEAR_LEVEL_CHOICES = [
    (1, "1st"),
    (2, "2nd"),
    (3, "3rd"),
    (4, "4th"),
]

STUDENT_CLASSIFICATION_CHOICES = [
    (1, "New"),
    (2, "Continuing"),
    (TRANSFEREE_INDEX, "Transferee"),
    (4, "Returnee"),
    (5, "Cross Enrollee"),
    (6, "Shiftee From"),
]

REGISTRATION_STATUS_CHOICES = [
    (1, "Regular"),
    (2, "Irregular")
]

SEX_CHOICES = [
    (1, "Male"),
    (2, "Female")
]

SCHOOL_TYPE_CHOICES = [
    (1, "Private"),
    (2, "Public")
]

class YearLevel(models.IntegerChoices):
    FIRST = 1, _('First')
    SECOND = 2, _('Second')
    THIRD = 3, _('Third')
    FOURTH = 4, _('Fourth')


class Section(models.Model):
    id = models.BigAutoField(db_column="id", primary_key=True)
    section_name = models.CharField(unique=True, max_length=100)

    def __str__(self):
        return self.section_name


class Department(models.Model):
    id = models.BigAutoField(db_column="dept_id", primary_key=True)
    name = models.CharField(unique=True, max_length=255)

    def __str__(self):
        return self.name


class Subject(models.Model):
    subject_name = models.CharField(max_length=50)
    unit = models.IntegerField()

    def __str__(self):
        return self.subject_name


class Course(models.Model):
    id = models.BigAutoField(db_column="course_id", primary_key=True)
    course_name = models.CharField(unique=True, max_length=100)
    course_abbr = models.CharField(
        db_column="course_abbr", max_length=20, blank=True, default=""
    )
    course_department = models.ForeignKey(
        Department,
        on_delete=models.SET_NULL,
        db_column="course_department_id",
        null=True,
    )
    course_credit = models.PositiveSmallIntegerField()

    subjects = models.ManyToManyField(Subject, blank=True)

    def __str__(self):
        return self.course_name


class Record(models.Model):
    user = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, blank=True, null=True)
    first_name = models.CharField(default="", blank=False, max_length=50)
    middle_name = models.CharField(blank=True, max_length=50)
    last_name = models.CharField(default="", blank=False, max_length=50)
    home_address = models.CharField(default="", blank=False, max_length=150)
    landline_no = PhoneNumberField(blank=True, region="PH")
    cellphone_no = PhoneNumberField(blank=True, region="PH")
    email = models.EmailField(max_length=254, blank=True)
    course = models.ForeignKey(
        Course, on_delete=models.SET_NULL, blank=True, null=True)
    section = models.ForeignKey(
        Section, on_delete=models.SET_NULL, blank=True, null=True
    )
    student_classification = models.PositiveIntegerField(
        default=1, choices=STUDENT_CLASSIFICATION_CHOICES)
    registration_status = models.PositiveIntegerField(
        default=1, choices=REGISTRATION_STATUS_CHOICES)
    shiftee_from = models.CharField(max_length=150, blank=True)
    birthday = models.DateField(default=now)
    birthplace = models.CharField(default="", blank=False, max_length=150)
    age = models.PositiveIntegerField(default=18, blank=False, validators=[
                                      MaxValueValidator(100), MinValueValidator(12)])
    sex = models.PositiveIntegerField(default=1, choices=SEX_CHOICES)
    religion = models.CharField(default="", blank=True, max_length=50)
    nationality = models.CharField(default="", blank=True, max_length=50)
    civil_status = models.CharField(default="", blank=True, max_length=50)

    school_elementary = models.CharField(
        default="", blank=True, max_length=150)
    school_year_elemetary = models.PositiveIntegerField(default=datetime.datetime.now().year, blank=True, validators=[
        MaxValueValidator(3000), MinValueValidator(1985)])
    school_access_elementary = models.PositiveIntegerField(
        default=1, choices=SCHOOL_TYPE_CHOICES)
    school_address_elementary = models.CharField(
        default="", blank=True, max_length=150)

    school_high = models.CharField(default="", blank=True, max_length=150)
    school_year_high = models.PositiveIntegerField(default=datetime.datetime.now().year, blank=True, validators=[
        MaxValueValidator(3000), MinValueValidator(1985)])
    school_access_high = models.PositiveIntegerField(
        default=1, choices=SCHOOL_TYPE_CHOICES)
    school_address_high = models.CharField(
        default="", blank=True, max_length=150)

    school_last_attended = models.CharField(
        default="", blank=True, max_length=150)
    school_last_attended_address = models.CharField(
        default="", blank=True, max_length=150)

    parent_guardian = models.CharField(default="", blank=True, max_length=50)
    parent_address = models.CharField(default="", blank=True, max_length=150)
    parent_occupation = models.CharField(default="", blank=True, max_length=50)
    parent_landline_no = PhoneNumberField(blank=True, region="PH")
    parent_cellphone_no = PhoneNumberField(blank=True, region="PH")

    year_level = models.PositiveIntegerField(
        choices=YEAR_LEVEL_CHOICES, blank=False, default=1)
    school_year = models.PositiveIntegerField(default=datetime.datetime.now().year, blank=False, validators=[
        MaxValueValidator(3000), MinValueValidator(2000)])
    semester = models.PositiveIntegerField(
        choices=SEMESTER_CHOICES, blank=False, default=1)
    approved = models.BooleanField(default=False)

    form_137 = models.FileField(
        blank=True, upload_to='documents/')

    card_138 = models.FileField(
        blank=True, upload_to='documents/')

    goodmoral = models.FileField(
        blank=True, upload_to='documents/')

    notice_of_admission = models.FileField(
        blank=True, upload_to='documents/')

    medical_clearance = models.FileField(
        blank=True, upload_to='documents/')

    application_form = models.FileField(
        blank=True, upload_to='documents/')

    transcript_of_record = models.FileField(
        blank=True, upload_to='documents/')

    notice_of_admission = models.FileField(
        blank=True, upload_to='documents/')

    cert_of_transfer = models.FileField(
        blank=True, upload_to='documents/')

    registration_date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'semester', 'year_level', 'school_year')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('records:record-update', kwargs={'pk': self.pk})

    def save_model(self, request, obj, form, change):
        if not obj.pk:
            # Only set added_by during the first save.
            obj.user = request.user
        super().save_model(request, obj, form, change)


class FormsApproval(models.Model):
    record = models.ForeignKey(
        Record, on_delete=models.CASCADE)

    form_137 = models.BooleanField(default=False)
    card_138 = models.BooleanField(default=False)
    goodmoral = models.BooleanField(default=False)
    notice_of_admission = models.BooleanField(default=False)
    medical_clearance = models.BooleanField(default=False)
    application_form = models.BooleanField(default=False)
    transcript_of_record = models.BooleanField(default=False)
    notice_of_admission = models.BooleanField(default=False)
    cert_of_transfer = models.BooleanField(default=False)

    def __str__(self):
        return f'Forms Approval {self.id}'


def create_forms_approval(sender, instance, created, **kwargs):
    if created:
        FormsApproval.objects.create(record=instance)


signals.post_save.connect(create_forms_approval, sender=Record, weak=False,
                          dispatch_uid='models.create_forms_approval')

records/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from records.forms import RecordForm
from records.tables import RecordsTable
from .models import FormsApproval, Record
from records.choices import department_choices
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
import datetime
from django.forms.models import model_to_dict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.contrib import messages


def enrollment(request):
    if request.user is None or request.user.is_authenticated is False:
        return redirect('/accounts/login')

    records = Record.objects.filter(user=request.user)

   #  paginator = Paginator(records, 20)
   #  page = request.GET.get('page')
   #  paged_records = paginator.get_page(page)

   #  context = {
   #      'records': paged_records
   #  }

    table = RecordsTable(records)

    return render(request, 'records/records.html', {
        "table": table
    })


def record(request, record_id):
    record = get_object_or_404(Record, pk=record_id)

    context = {
        'record': record
    }

    return render(request, 'records/record.html', context)


class RecordFormView(FormView):
    template_name = 'enrollment/enrollment.html'
    form_class = RecordForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return super().form_valid(form)


class RecordCreateView(LoginRequiredMixin, CreateView):
    model = Record
    form_class = RecordForm
    success_url = reverse_lazy('records:enrollment')

    def form_valid(self, form):
        form.instance.user = self.request.user
        try:
            form.save()
        except Exception as exception:
            if (exception.args[0] == 1062):
                form.add_error(
                    None, "You already enrolled with the same semester and school year! Select a different semester or school year")
            return self.form_invalid(form)
        return super(RecordCreateView, self).form_valid(form)

    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     self.object.user = self.request.user
    #     self.object.save()
    #     return HttpResponseRedirect(self.get_success_url())

    # def post(self, request, *args, **kwargs):
    #     form = RecordForm(request.POST)
    #     if form.is_valid():
    #         book = form.save()
    #         book.save()
    #         return HttpResponseRedirect(self.get_success_url())
    #     return render(request, 'records/record_form.html', {'form': form})

    def form_invalid(self, form):
        response = super().form_invalid(form)
        messages.error(self.request, form.errors)
        if self.request.accepts('text/html'):
            return response
        else:
            return JsonResponse(form.errors, status=400)

    # def get_form(self, *args, **kwargs):
    #     try:
    #         latest_record = Record.objects.filter(
    #             user=self.request.user).order_by('school_year').reverse().first()

    #         if (latest_record is not None and latest_record.school_year == datetime.datetime.now().year):
    #             self.object = latest_record
    #     except (Record.DoesNotExist):
    #         pass

    #     return super().get_form(*args, **kwargs)

    # def get_initial(self, *args, **kwargs):
    #     initial = super(RecordCreateView, self).get_initial(**kwargs)
    #     try:
    #         latest_record = Record.objects.filter(
    #             user=self.request.user).order_by('school_year').reverse().first()
    #         if (latest_record is not None and latest_record.school_year != datetime.datetime.now().year):
    #             initial = model_to_dict(latest_record)
    #     except (Record.DoesNotExist):
    #         pass

    #     return initial


class RecordUpdateView(UpdateView):
    model = Record
    form_class = RecordForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        try:
            form.save()
        except Exception as exception:
            if (exception.args[0] == 1062):
                form.add_error(
                    None, "You already enrolled with the same semester and school year! Select a different semester or school year")
            return self.form_invalid(form)
        return super(UpdateView, self).form_valid(form)

    def form_invalid(self, form):
        response = super().form_invalid(form)
        messages.error(self.request, form.errors)
        if self.request.accepts('text/html'):
            return response
        else:
            return JsonResponse(form.errors, status=400)


class RecordDeleteView(DeleteView):
    model = Record
    success_url = reverse_lazy('record-list')


def get_current_semester():
    current_month = datetime.datetime.now().month
    current_semester = int((current_month / 3) + 1)
    return current_semester


def get_enrollment(request):
    current_semester = get_current_semester()

    return redirect('/enrollment/add')

templates/records/record_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block mycss %} 
    <style>
        .form-icon{
            max-width:40%;
        }
        .csvu_title {
            font-family: "Times New Roman", Times, serif;
        }
        hr {
            height: 12px;
            background: black;
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/common.css' %}" />
{% endblock mycss %}

{% block content %}

    <div class="container">
        
        <div class="row">
            <form method="POST" enctype="multipart/form-data" class="row pt-1">
                <div class="row">
                    <div class="col-4">
                        <img src="{% static 'img/diit.png' %}" class="mx-auto d-block form-icon" alt="cvsu logo">
                    </div>
                    <div class="col-auto">
                        <p class="fs-6 text-center fs-normal lh-1">Republic of the Philippines</p>
                        <p class="fs-3 text-center fs-bolder lh-1 text-uppercase csvu_title">Cavite State University</p>
                        <p class="fs-6 text-center fs-bolder lh-1">Silang Campus</p>
                        <p class="fs-6 text-center fs-normal lh-1">Biga I, Silang, Cavite</p>
                        <p class="fs-5 text-center fs-bold lh-1 text-uppercase mb-5">Student Information Sheet</p>
                    </div>
                </div>
                
                {% if form.non_field_errors  %}
                    <ul>
                    {% for error in form.non_field_errors  %}
                        <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                    </ul>
                {% else %}
                    {% if form.errors  %}
                        <p>Please correct the following data form fields:</p>
                        <ul>
                        {% for error in form.errors  %}
                            <li class="text-danger">{{ error }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endif %}

                <p>Instruction: Input N/A if not applicable<br>*required fields</p>
                <!-- Security token -->
                {% csrf_token %}
                <div class="col-md-4">
                    {{form.last_name|as_crispy_field}}
                </div>
                <div class="col-md-4">
                    {{form.first_name|as_crispy_field}}
                </div>
                <div class="col-md-4">
                    {{form.middle_name|as_crispy_field}}
                </div>
                <div class="col-md-12">
                    {{form.home_address|as_crispy_field}}
                    <p class="fst-italic">
                        House No. & Street / Barangay / Town / Province
                    </p>
                </div>
                <div class="col-md-6">
                    {{form.landline_no|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.cellphone_no|as_crispy_field}}
                </div>
                <div class="col-md-12">
                    {{form.email|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.course|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.section|as_crispy_field}}
                </div>
                <div class="col-md-12">
                    {{form.student_classification|as_crispy_field}}
                </div>
                <div class="col-md-12">
                    {{form.shiftee_from|as_crispy_field}}
                </div>
                <div class="col-md-12">
                    {{form.registration_status|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.birthday|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.birthplace|as_crispy_field}}
                </div>
                <div class="col-md-2">
                    {{form.age|as_crispy_field}}
                </div>
                <div class="col-md-2">
                    {{form.sex|as_crispy_field}}
                </div>
                <div class="col-md-2">
                    {{form.religion|as_crispy_field}}
                </div>
                <div class="col-md-2">
                    {{form.nationality|as_crispy_field}}
                </div>
                <div class="col-md-2">
                    {{form.civil_status|as_crispy_field}}
                </div>
                <p class="fs-4">Educational Background</p>
                <div class="row justify-content-md-right">
                    <div class="col-md-10">
                        {{form.school_elementary|as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.school_year_elemetary|as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.school_access_elementary|as_crispy_field}}
                    </div>
                    <div class="col-md-10">
                        {{form.school_address_elementary|as_crispy_field}}
                    </div>

                    <div class="col-md-10">
                        {{form.school_high|as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.school_year_high|as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.school_access_high|as_crispy_field}}
                    </div>
                    <div class="col-md-10">
                        {{form.school_address_high|as_crispy_field}}
                    </div>

                    <p class="fs-5">For Transferees/Cross Enrollees</p>
                    <div class="col-md-10">
                        {{form.school_last_attended|as_crispy_field}}
                    </div>
                    <div class="col-md-10">
                        {{form.school_last_attended_address|as_crispy_field}}
                    </div>                    
                </div>
                <hr>
                <div class="col-md-12">
                    {{form.parent_guardian|as_crispy_field}}
                </div>
                <div class="col-md-12">
                    {{form.parent_address|as_crispy_field}}
                </div>
                <div class="col-md-12">
                    {{form.parent_occupation|as_crispy_field}}
                </div>

                <div class="col-md-6">
                    {{form.parent_landline_no|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.parent_cellphone_no|as_crispy_field}}
                </div>
                <hr>
                <div class="col-md-4">
                    {{form.year_level|as_crispy_field}}
                </div>
                <div class="col-md-4">
                    {{form.semester|as_crispy_field}}
                </div>
                <div class="col-md-4">
                    {{form.school_year|as_crispy_field}}
                </div>
                <div class="row">
                    <div class="col-4 mb-5">
                        <input type="submit" class="btn btn-success" value="Submit">
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(function() {
            let student_classification_value = $('#id_student_classification').val();
            update_shiftee_visibility(student_classification_value);

            $('#id_student_classification').on('change', function (e) {
                var valueSelected = this.value;

                update_shiftee_visibility(valueSelected);
            });

            function update_shiftee_visibility(valueSelected){
                if (valueSelected === "6"){
                    $('#div_id_shiftee_from').show();
                } else {
                    $('#div_id_shiftee_from').hide();
                }
            }
        });
    </script>
{% endblock %}

templates/records/records.html
{% extends 'base.html' %} {% load static %} {% block mycss %}
<link rel="stylesheet" href="{% static 'css/common.css' %}" />
{% endblock mycss %} {% block content %}

<div class="container">
  <h1>Your Enrollments</h1>
  <a class="btn btn-success" href="{% url 'records:record-add' %}"
    >New Enrollment</a
  >
</div>

{% load django_tables2 %} {% render_table table %} {% endblock %}

templates/records/search.html
{% extends 'base.html' %}

{% block content %}

    <section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
        <div class="row text-center">
        <div class="col-md-12">
                <form action="{% url 'search' %}">
                    <!-- Form Row 1 -->
                    <div class="form-row">
                    <div class="col-md-12 mb-3">
                        <label class="sr-only">Search</label>
                        <input type="text" name="name" value="{{values.name}}"  class="form-control" placeholder="Search Using Name....">
                    </div>
                    <div class="col-md-4 mb-3">
                        <label class="sr-only">ID</label>
                        <input type="text" name="roll" value="{{values.roll}}" class="form-control" placeholder="Class Roll....">
                    </div>

                    <div class="col-md-4 mb-3">
                        <label class="sr-only">Batch</label>
                        <input type="text" name="batch" value="{{values.batch}}" class="form-control" placeholder="Batch....">
                    </div>

                <div class="col-md-4 mb-3">
                    <label class="sr-only">Department</label>
                    <select name="department" class="form-control">
                    <option selected="true" disabled="disabled">Select Department</option>
                    {% for key,value in department_choices.items %}
                        <option value="{{ key }}" 
                        {% if key == values.department %}
                            selected
                        {% endif %}>{{value}}
                        </option>
                    {% endfor %}
                    </select>
                </div>
                </div>
                <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
        </div>
        </div>
    </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            <a href="{% url 'index' %}">
                <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="{% url 'records' %}">Query</a>
            </li>
            <li class="breadcrumb-item"> Search Results</li>
        </ol>
        </nav>
    </div>
    </section>

    <!-- Listings -->
    <section id="listings" class="py-4">
    <div class="container">
        <div class="row">

            <!-- Listing 1 -->
            <div class="col-md-12 col-lg-12 mb-12">
                <div class="searchheading listing-preview">
                    <div class="row text-center">
                        <div class="col-md-4">
                            <p>Name</p>
                        </div>
                        <div class="col-md-2">
                            <p>ID</p>
                        </div>
                        <div class="col-md-2">
                            <p>Batch</p>
                        </div>
                        <div class="col-md-2">
                            <p>Department</p>
                        </div>
                        <div class="col-md-2">
                            <p>Action</p>
                        </div>
                    </div>
                </div>


                {% if records %}

                    {% for record in records %}

                        <div class="listing-preview searchlist text-center">
                        <div class="row">
                            <div class="col-md-4 text-left">
                                <a href="{% url 'record' record.id  %}"><p>{{record.name}}</p></a>
                            </div>
                            <div class="col-md-2">
                                <p>{{record.roll}}</p>
                            </div>
                            <div class="col-md-2">
                                <p>{{record.batch}}</p>
                            </div>
                            <div class="col-md-2">
                                <p>{{record.department}}</p>
                            </div>
                            <div class="col-md-2">
                                <p>
                                    <a href="{% url 'record' record.id  %}"><button class="infobut" data-toggle="modal" data-target="#inquiryModal">More Info</button></a></p>
                            </div>
                        </div>
                        </div>

                    {% endfor %}

                {% else %}
                    <div class="col-md-12">
                        <p>No Records Available</p>
                    </div>
                {% endif %}


            <!--Pagination-->
            <div class="row">
                <div class="col-md-12">
                {% if records.has_other_pages %}
                    <ul class="pagination">
                        {% if records.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{records.previous_page_number}}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link">&laquo;</a>
                            </li>
                        {% endif %}

                        {% for i in records.paginator.page_range %}
                            {% if records.number == i %}
                                <li class="page-item active">
                                    <a class="page-link">{{i}}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        
                        {% if records.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{records.next_page_number}}">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link">&raquo;</a>
                            </li>
                        {% endif %}
                        
                    </ul>
                {% endif %}
                </div>
            </div>

        </div>
    </div>
    </section>

{% endblock %}